### ISSUE TITLE
Multi threaded 😎

### ISSUE THREAD

**Issue by bstar16** [RemainingToast/auscpvp-issues#5]
Toast can 100% pull this off

**Comment by bstar16** [comment]
Pretty ambitious thing for someone to do but would be cool

**Comment by RhysyPiece360** [comment]
Minecraft only uses 1 therad there is software though

**Comment by RemainingToast** [comment]
Yeah probably won't happen unless Minecraft or Paper themselves add multithreading for the whole game the best I can do is mob ai multithreading.

**Comment by RemainingToast** [comment]
not happening
